{{- if .Values.comfyUI.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-comfyui
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: comfyui
  ports:
    - port: 80
      targetPort: 8188
      name: web
    - port: 8000
      targetPort: 8000
      name: api
  type: ClusterIP
{{- end }}