apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-ollama
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ollama
  ports:
    - port: 80
      targetPort: 11434  # Adjust to Ollama default API port as needed
  type: ClusterIP