{{- if .Values.openWebUI.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: openwebui-sso-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- if eq .Values.openWebUI.sso.provider "google" }}
  GOOGLE_CLIENT_SECRET: {{ .Values.openWebUI.sso.google.clientSecret | b64enc | quote }}
  {{- else if eq .Values.openWebUI.sso.provider "microsoft" }}
  MICROSOFT_CLIENT_SECRET: {{ .Values.openWebUI.sso.microsoft.clientSecret | b64enc | quote }}
  {{- else if eq .Values.openWebUI.sso.provider "github" }}
  GITHUB_CLIENT_SECRET: {{ .Values.openWebUI.sso.github.clientSecret | b64enc | quote }}
  {{- else if eq .Values.openWebUI.sso.provider "oidc" }}
  OAUTH_CLIENT_SECRET: {{ .Values.openWebUI.sso.oauth.clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
