apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openWebUI.auth.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  WEBUI_SECRET_KEY: {{ .Values.openWebUI.auth.secretKey | b64enc }} 