apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-device-plugin-config
  namespace: kube-system
data:
  timeslice-jetson.yaml: |
    version: v1
    sharing:
      timeSlicing:
        renameByDefault: false
        resources:
          - name: nvidia.com/gpu
            replicas: 5
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
  labels:
    name: nvidia-device-plugin-ds
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      priorityClassName: system-node-critical
      runtimeClassName: nvidia
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - name: nvidia-device-plugin-ctr
        image: nvcr.io/nvidia/k8s-device-plugin:v0.20.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: PASS_DEVICE_SPECS
          value: "true"
        - name: FAIL_ON_INIT_ERROR
          value: "false"
        args:
        - --config-file=/etc/nvidia/time-slice/timeslice-jetson.yaml
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
        - name: plugin-config
          mountPath: /etc/nvidia/time-slice
          readOnly: true
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/snap/microk8s/common/var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
      - name: plugin-config
        configMap:
          name: nvidia-device-plugin-config
